apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smtp-pself
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  subject:
    organizations:
      - Sfera-T1
  commonName: {{ .Values.certificate.commonName }}
  dnsNames: {{ .Values.certificate.DNS }}
  issuerRef:
    name: smtp
    kind: Issuer
