apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: smtp
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
spec:
  selfSigned: {}
