apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  name: smtps-mailhog-stun
spec:
  {{- with .Values.service.clusterIP }}
  clusterIP: "{{ . }}"
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ . }}"
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - name: {{ .Values.containerPort.smtps.name }}
    port: {{ .Values.containerPort.smtps.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPort.smtps.port }}
  selector:
    {{- include "mailhog.selectorLabels" . | nindent 4 }}
  type: ClusterIP
